### ISSUE TITLE
Any appetite for expanding env vars?

### ISSUE THREAD

**Issue by ghost** [kopeio/kexpand#15]
- values.yaml
``` yaml
environment: uat
```

- service.yml

``` yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: my-namespace
  labels:
    app: my-app
    env: $((environment))
    version: "${BUILD_NUMBER}"
  annotations:
    domainName: "$((environment))-my-app.my-domain.com"
    commited_by: "${USER}"
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: my-app
  sessionAffinity: ClientIP
  type: LoadBalancer
```

- would produce:

``` yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: my-namespace
  labels:
    app: my-app
    env: uat
    version: "jenkins-build-number"
  annotations:
    domainName: "uat-my-app.my-domain.com"
    commited_by: "my-unix-id"
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: my-app
  sessionAffinity: ClientIP
  type: LoadBalancer
```

I'm thinking  the first pass would merge the var file, the second pass would merge from env. Non-matched env vars would be ignored and passed along as literal.

@justinsb Thoughts?
