### ISSUE TITLE
Numerical values without quotes are auto-expanded to floating points with exponents

### ISSUE THREAD

**Issue by ghost** [kopeio/kexpand#18]
# Question - Should unquoted numbers be converted to floats?

- `templates/svc.yml`:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  labels:
    app: my-app
    dns: route53
  annotations:
    domainName: $(domain_name)
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::$((aws_account)):server-certificate/$((domain_name))
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: my-app
  sessionAffinity: ClientIP
  type: LoadBalancer
```

- `vars/uat-svc.yml`:

```yaml
---
domain_name: my-app.my-domain.com
aws_account: 012345678901
```

- render out the result:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  labels:
    app: my-app
    dns: route53
  annotations:
    domainName: "my-app.my-domain.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::1.2345678901e+10:server-certificate/my-app.my-domain.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: my-app
  sessionAffinity: ClientIP
  type: LoadBalancer
```

- Quoting the vars `aws_account: "012345678901"` resulted in the right output render

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
  labels:
    app: my-app
    dns: route53
  annotations:
    domainName: "my-app.my-domain.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::012345678901:server-certificate/my-app.my-domain.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: my-app
  sessionAffinity: ClientIP
  type: LoadBalancer
```

Is this the desired behavior?
